<?php
/** op-app-skeleton-2020-nep:/end-point/sub-directory/index.phtml
 *
 * @created   2022-12-30
 * @version   1.0
 * @package   op-app-skeleton-2020-nep
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** Declare strict
 *
 */
declare(strict_types=1);

/** namespace
 *
 */
namespace OP;

/* @var $passed_smart_url_args array */

?>
<h1>Sub directory</h1>
<p>This page's end-point file is : <?= __DIR__ ?>/index.php</p>
<p>Please visit in this directory another page.
	<a href="./another">./another</a>
</p>
