<?php
/**
 * app-skeleton-2018-nep:/asset/bootstrap/php/content.phtml
 *
 * @creation  2018-12-14
 * @version   1.0
 * @package   core
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
//	Correspond to  Eclipse undefined error.
if( false ){
	$module = null;
};
?>
<section>
	<h1>Does not install php-<?= $module ?> module.</h1>
	<p>Please install php-<?= $module ?> module.</p>
	<?php
	switch( PHP_OS ){ // PHP 7.2.0 --> PHP_OS_FAMILY
		case 'MacOS':
		case 'Darwin':
			include('content-osx.phtml');
			break;

		case 'WIN32':
		case 'WINNT':
			include('content-win.phtml');
			break;

		case 'AIX':
		case 'Linux':
		case 'SunOS':
			include('content-unix.phtml');
			break;

		default:
			var_dump(PHP_OS);
			break;
	}
	?>
</section>
