<?php
/** op-module-bootstrap:/php/module-unix.phtml
 *
 * @created   2018-11-13
 * @version   1.0
 * @package   op-module-bootstrap
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
//	...
$t = explode('.', PHP_VERSION);
$v = $t[0].$t[1];

//	...
$redhat = file_exists('/etc/redhat-release') ?? false;
$remi   = $v > 53 ? true: false;
$repo   = $remi ? "--enablerepo=remi-php{$v}": ' ';

?>
<pre><code>
<?php if( $redhat ): ?>
sudo yum<?= $repo ?>install php-<?= _OP_APP_BOOTSTRAP_ . PHP_EOL ?>
sudo service httpd restart
<?php endif; ?>
</code></pre>
