<?php
/** op-module-bootstrap:/php/module.phtml
 *
 * @created   2016-11-16
 * @version   1.0
 * @package   op-module-bootstrap
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<!doctype html>
<html>
	<head>
		<style>
		pre {
			margin:0 1em;
			padding:0.5em;
			background-color:#dfdfdf;
			border: 1px solid #cfcfcf;
			border-radius: 0.25em;
		}
		</style>
	</head>
	<body>
		<section>
			<h1>Does not install php-<?= _OP_APP_BOOTSTRAP_ ?> module.</h1>
			<p>Please install php-<?= _OP_APP_BOOTSTRAP_ ?> module.</p>
			<?php
			switch( PHP_OS ){ // PHP 7.2.0 --> PHP_OS_FAMILY
				case 'MacOS':
				case 'Darwin':
					include('module-osx.phtml');
					break;

				case 'WIN32':
				case 'WINNT':
					include('module-win.phtm.phtml');
					break;

				case 'AIX':
				case 'Linux':
				case 'SunOS':
					include('module-unix.phtml');
					break;

				default:
					var_dump(PHP_OS);
					break;
			}
			?>
		</section>
	</body>
</html>
<?php
exit();
