<?php
/**
 * app-skeleton-2018-nep:/asset/bootstrap/php/index.phtml
 *
 * @creation  2016-11-16
 * @version   1.0
 * @package   core
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<!doctype html>
<html>
	<head>
		<style>
		pre {
			margin:0 1em;
			padding:0.5em;
			background-color:#dfdfdf;
			border: 1px solid #cfcfcf;
			border-radius: 0.25em;
		}
		</style>
	</head>
	<body>
	<?php include(__DIR__.'/content.phtml') ?>
	</body>
</html>
<?php
exit();
