<?php
/** op-app-skeleton-2020-nep:/asset/template/google/adsense.phtml
 *
 * @created   2020-07-11
 * @version   1.0
 * @package   op-app-skeleton-2020-nep
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

 /** namespace
 *
 */
namespace OP;

//	...
$config = Config::Get('google');

//	...
if(!$adsense_id = $config['adsense']['id'] ?? null ){
	echo PHP_EOL.'<!-- Empty Google AdSense ID -->'.PHP_EOL;
	return;
}

?>
<!-- Google AdSense -->
<script src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js" defer></script>
<script>
(adsbygoogle = window.adsbygoogle || []).push({
	google_ad_client: "<?= $adsense_id ?>",
	enable_page_level_ads: true
});
</script>
