<?php
/** op-skeleton-2020:/asset/template/google/analytics.phtml
 *
 * @created   2017-07-28
 * @updated   2019-04-03
 * @version   1.0
 * @package   op-skeleton-2020
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

 /** namespace
 *
 * @created   2019-04-03
 */
namespace OP;

//	...
if( Env::isLocalhost() ){
	echo '<!-- Google analytics tracking is skipped. (localhost) -->'.PHP_EOL;
	return;
}

//	...
if(!$tracking_id = Config::Get('google')['analytics']['id'] ?? null ){
	echo '<!-- Google analytics tracking id is empty. -->'.PHP_EOL;
	return;
};

?>
<!-- Google analytics -->
<script>
<?php /* prepare */ ?>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

<?php /* execute */ ?>
ga('create','<?= $tracking_id ?>','auto');
ga('send','pageview');

<?php /* user tracking */ ?>
<? if( $user_id = Cookie::UserID() ): ?>
ga('set','&uid','<?= $user_id ?>');
<? endif; ?>
</script>
