<?php
/** op-app-skeleton-2020-nep:/asset/bootstrap/app/config-admin.phtml
 *
 * @created   2020-07-24
 * @version   1.0
 * @package   op-app-skeleton-2020-nep
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<!doctype html>
<html>
	<head>
		<style>
		pre {
			margin:0 1em;
			padding:0.5em;
			background-color:#dfdfdf;
			border: 1px solid #cfcfcf;
			border-radius: 0.25em;
		}

		.margin.left {
			margin-left: 1em;
		}
		</style>
	</head>
	<body>
		<section>
			<h1>The admin config file has not been set.</h1>

			<p class="margin left">File path is</p>
			<pre class="margin left">asset:/config/admin.php</pre>

			<p class="margin left">Description is</p>
<pre class="margin left">&lt;?php
return [
  OP\Env::_ADMIN_IP_   => '127.0.0.1',
  OP\Env::_ADMIN_MAIL_ => 'to_address@example.com',
  OP\Env::_MAIL_FROM_  => 'from_address@example.com'
];
?&gt;</pre>
		</section>
	</body>
</html>
<?php
exit();
