<?php
/** op-module-bootstrap:/app/config-admin.phtml
 *
 * @created   2020-07-24
 * @version   1.0
 * @package   op-module-bootstrap
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

//	...
namespace OP;

//	...
$path = OP::MetaPath('asset:/config/admin.php');

//	...
$file = file_get_contents($path);
//	Remove only 1st multi line comment.
$file = preg_replace('/\/\*\*[\s\S]*?\*\/\n/', '', $file, 1);
//	Remove /* and */
$file = str_replace(["\n/*\n","\n*/\n"], "\n", $file);

//	...
if( Env::isCI() ){
	//	Create admin config file.
	if(!$io = file_put_contents($path = OP::MetaPath('asset:/config/').'_admin.php',  OP::Decode($file)) ){
		echo "Could not write to this file. ({$path})";
	}
	return $io ? true: false;
}

//	...
if( Env::isShell() ){
	echo "Please edit this file: {$path}\n";
	return false;
}

?>
<?php include(__DIR__.'/../html_head.phtml') ?>
		<section>
			<h1>The admin config file has not been set.</h1>

			<p>File path is</p>
			<div class="code"><code><?= $path ?></code></div>

			<p>Configuration is</p>
			<div class="code"><pre><code><?= OP::Encode($file) ?></code></pre></div>
		</section>
<?php include(__DIR__.'/../html_foot.phtml') ?>
<?php
return false;
