<?php
/** op-module-bootstrap:/app/config-admin.phtml
 *
 * @created   2020-07-24
 * @version   1.0
 * @package   op-module-bootstrap
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

//	...
namespace OP;

//	...
$path = OP::MetaPath('asset:/config/admin.php');

//	...
$file = file_get_contents($path);
$file = Encode($file);
$file = preg_replace(['|\/\*\* .+|','| \*.+|','| \*|','|\n/\*|','|\n\*/|'], '', $file);
$file = preg_replace(['|//\t|','|\t|','|\n+|','|,\n|','|,\n\n\]|'], ['//  ','    ',"\n",",\n\n",",\n]"], $file);

//	...
if( Env::isCI() ){
	//	...
	if(!file_put_contents(OP::MetaPath('asset:/config/').'_admin.php',  OP::Decode($file)) ){
		echo 'Could not write to this file. (asset:/config/_admin.php)';
		exit(__LINE__);
	}
	//	...
	return;
}
?>
<?php include(__DIR__.'/../html_head.phtml') ?>
		<section>
			<h1>The admin config file has not been set.</h1>

			<p>File path is</p>
			<div class="code"><code><?= $path ?></code></div>

			<p>Configuration is</p>
			<div class="code"><pre><code><?= $file ?></code></pre></div>
		</section>
<?php include(__DIR__.'/../html_foot.phtml') ?>
