<?php
/** op-module-bootstrap:/app/gitsubmodule.phtml
 *
 * @created   2020-07-13
 * @version   1.0
 * @package   op-module-bootstrap
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 */
namespace OP;

//	..
$m1 = 'Not initializing git submodule';
$m2 = 'Execute the following command.';
$c1 = 'cd '.dirname($_SERVER['SCRIPT_FILENAME']);
$c2 = 'sh ./asset/git/submodule/init.sh';

//	...
if( basename($_SERVER['SCRIPT_FILENAME']) === 'ci.php' ){
	echo '0' . PHP_EOL;
	echo $c1 . PHP_EOL;
	echo $c2 . PHP_EOL;
	return;
}

//	...
if( isset($_SERVER['SHELL']) ){
	echo PHP_EOL;
	echo $m1 . PHP_EOL;
	echo $m2 . PHP_EOL;
	echo PHP_EOL;
	echo '1: ' . $c1 . PHP_EOL;
	echo '2: ' . $c2 . PHP_EOL;
	return;
}
?>
<?php include(__DIR__.'/../html_head.phtml') ?>
		<section>
			<h1><?= $m1 ?></h1>
			<p> <?= $m2 ?></p>
			<ol>
				<li><code class="code"><?= $c1 ?></code></li>
				<li><code class="code"><?= $c2 ?></code></li>
			</ol>
		</section>
<?php include(__DIR__.'/../html_foot.phtml') ?>
