<?php
/** op-module-bootstrap:/app/gitsubmodule.phtml
 *
 * @created   2020-07-13
 * @version   1.0
 * @package   op-module-bootstrap
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<!doctype html>
<html>
	<head>
		<style>
		pre {
			margin:0 1em;
			padding:0.5em;
			background-color:#dfdfdf;
			border: 1px solid #cfcfcf;
			border-radius: 0.25em;
		}
		</style>
	</head>
	<body>
		<section>
			<h1>Not initializing git submodule</h1>
			<p>Execute the following command.</p>
			<pre>sh asset/gitsubmodule-init.sh</pre>
		</section>
	</body>
</html>
<?php
exit();
