<?php
/**
 * app-skeleton-2019-nep:/asset/template/google-analytics.phtml
 *
 * @creation  2017-07-28
 * @updation  2019-04-03
 * @version   1.0
 * @package   app-skeleton-2019-nep
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

 /** namespace
 *
 * @creation  2019-04-03
 */
namespace OP;

/* @var $app UNIT\App */

//	...
if(!$tracking_id = Env::Get('google')['analytics']['id'] ?? null ){
	echo '<!-- Google analytics tracking id is empty. -->'.PHP_EOL;
	return;
};

//	...
if( Env::isLocalhost() ){
	echo '<!-- Google analytics tracking is skipped. (localhost) -->'.PHP_EOL;
	return;
}
?>
<!-- Google analytics -->
<script>
<?php /* prepare */ ?>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

<?php /* execute */ ?>
ga('create','<?= $tracking_id ?>','auto');
ga('send','pageview');

<?php /* user traccking */ ?>
<? if( $user_id = $app->UserID() ): ?>
ga('set','&uid','<?= $user_id ?>');
<? endif; ?>
</script>
