<?php
/** op-module-bootstrap:/help.phtml
 *
 * @created   2020-07-26
 * @version   1.0
 * @package   op-module-bootstrap
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<h1>HTTP Server port check</h1>
<pre><code>
sudo lsof -nP -iTCP:80 -sTCP:LISTEN
</code></pre>

<h1>PHP-FPM port check</h1>
<pre><code>
sudo lsof -nP -iTCP:9000 -sTCP:LISTEN
sudo lsof -Pni4 | grep LISTEN | grep php
</code></pre>
