<?php
/** op-module-bootstrap:/html_head.phtml
 *
 * @created   2022-10-02
 * @version   1.0
 * @package   op-module-bootstrap
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<!doctype html>
<html>
<head>
	<title>Boot to the onepiece-framework</title>
	<style>
	<?php include(__DIR__.'/style.css') ?>
	</style>
</head>
<body>
<header>
	Boot to the onepiece-framework
</header>
<hr/>
