<?php
/** op-module-bootstrap:/op/rewrite-apache.phtml
 *
 * @created   2016-11-25
 * @version   1.0
 * @package   op-module-bootstrap
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

//	Remove URL Query. /file/path/?foo=bar --> /file/path/
$rewrite_base = explode('?', $_SERVER['REQUEST_URI'])[0];

//	Search app.php.
/* Why do need this code?
do{
	//	Check if document root.
	if( $rewrite_base === '/' ){
		break;
	}

	//	Generate app.php path.
	$path =  $_SERVER['DOCUMENT_ROOT'] . rtrim($rewrite_base,'/') .'/app.php';

	//	Check app.php path.
	if( file_exists($path) ){
		break;
	}

}while( $rewrite_base = dirname($rewrite_base) );
*/

//	Calc app root. /www/htdocs/ --> /www/htdocs + /file/path/ <-- /file/path
$app_root = rtrim($_SERVER['DOCUMENT_ROOT'],'/') . rtrim($rewrite_base,'/').'/';

//	Search .htaccess.
$i    = 0;
$file = fopen('.htaccess', 'r');
while( $line = fgets($file) ){
	//	...
	$i++;

	//	...
	if( preg_match('/RewriteEngine/', $line) ){
		$n1 = $i;
	};

	//	...
	if( preg_match('/RewriteBase/', $line) ){
		$n2 = $i;
	};
};
?>
<div data-translate="popup">
<h1>How to boot the onepiece-framework at the Apache web server.</h1>
<ol>
	<li>
		<p>Open <b data-i18n="false">"<?= $app_root ?>.htaccess"</b> file.</p>
		<p><i><b>Attention!</b> This file is invisible file.</i></p>
	</li>
	<li>
		<p>
			Look for line <?= $n1 ?>.<br/>
			Change the value of <b data-i18n="false">"RewriteEngine"</b> to <b data-i18n="false">"On"</b> from <b data-i18n="false">"Off"</b>.
		</p>
	</li>
	<?php if( $rewrite_base !== '/' ): ?>
	<li>
		<p>
			Look for line <?= $n2 ?>.<br/>
			Change the value of <b data-i18n="false">"RewriteBase"</b> to <b data-i18n="false">"<?= $rewrite_base ?>"</b> from <b data-i18n="false">"/"</b>.
		</p>
	</li>
	<?php endif; ?>
	<li>
		<p>
			Save <b data-i18n="false">.htaccess</b> file.
		</p>
	</li>
	<li>
		<p>
			Reload this page.
		</p>
	</li>
</ol>
</div>
