#!/usr/bin/env bash

# Calc git root
GIT_ROOT=`git rev-parse --show-superproject-working-tree`
if [ -z "$GIT_ROOT" ]; then
	GIT_ROOT=`git rev-parse --show-toplevel`
fi

# hook-the-hooks
HOOK_NAME=`basename $0`
${GIT_ROOT}/asset/git/hooks/hook-the-hooks.sh ${HOOK_NAME}

# Check if status
if [ $? -ne 0 ]; then
   exit 1
fi
