<?php
/**
 * app-skeleton-2020-nep:/asset/template/403_forbidden.phtml
 *
 * @created   2018-11-12
 * @version   1.0
 * @package   app-skeleton-2019-nep
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<section>
	<h2>403 Forbidden</h2>
	<p>You don't have permission to access.</p>
	<img src="<?= ConvertURL('app:/img/403.png') ?>"/>
</section>
