<?php
/** op-skeleton-2020:/asset/template/404_not_found.phtml
 *
 * @created   2017-08-29
 * @version   1.0
 * @package   op-skeleton-2020
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @created   2019-02-18
 */
namespace OP;

?>
<style>
.body .page404 p {
	margin: 1em 0;
	font-size: 110%;
}
</style>
<section id="page404" class="page404">
	<h2>404 Not found</h2>
	<p>This page for could not be found.</p>
	<img src="<?= ConvertURL('app:/img/404.png') ?>"/>
</section>
