<?php
/**
 * app-skeleton-2020-nep:/asset/template/404_not_found.phtml
 *
 * @created   2017-08-29
 * @version   1.0
 * @package   app-skeleton-2019-nep
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @created   2019-02-18
 */
namespace OP;

?>
<section id="page404" class="page404">
	<h2>404 Not found</h2>
	<p>This page for could not be found.</p>
	<img src="<?= ConvertURL('app:/img/404.png') ?>"/>
</section>
