<?php

/**
 * app-skeleton-2020-nep:/asset/template/app.phtml
 *
 * @created   2019-11-19
 * @version   1.0
 * @package   app-skeleton-2019-nep
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/**
 * namespace
 */
namespace OP;

/* @var integer $st */
$time = (microtime ( true ) - _OP_APP_START_);
$used = memory_get_usage () / 1000;
$peak = memory_get_peak_usage () / 1000;

?>
<script>
console.log('execute time: <?= $time ?>');
console.log('momory usage: <?= $used ?>KB (max: <?= $peak ?>KB)');
</script>
