<?php
/**
 * app-skeleton-2020-nep:/asset/template/welcome.phtml
 *
 * @created   2017-07-28
 * @version   1.0
 * @package   app-skeleton-2019-nep
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @created   2019-02-22
 */
namespace OP;

/* @var $app UNIT\App */
$app = Unit('App');
$app->Title('Welcome');

//	Get app root.
$app_root   = ConvertPath('app:/');
$asset_root = ConvertPath('asset:/');
$asset_path = null;

//	Calc asset path.
if( strpos($asset_root, $app_root) === 0 ){
	$asset_path = substr($asset_root, strlen($app_root));
}else{
	$asset_path = $asset_root;
}

?>
<style>
#welcome img {
	float: left;
	width: 10em;
	margin-right:  1em;
	margin-bottom: 1em;
}
</style>
<section id="welcome" data-i18n="true" data-i18n-locale="en:us">
	<!-- Introduction -->
	<h2>Welcome to the "onepiece-framework"!!</h2>
	<img src="<?= ConvertURL('app:/img/icon.png') ?>" />
	<p>
		Congratulations!
		onepiece-framework did booted!!
		How was it? Have you boot easily? So, The onepiece-framework is insanely great!!
		Because, the onepiece-framework is everything is intuitive.
	</p>
	<h3>The "NEW WORLD" is a new world.</h3>
	<p>
		For example, you can easily find the file of endpoint.
		Please try to find the running file from the URL of this page.
		It should be easy to find.
		Was it intuitive?
		You found it right away, right?
		This mechanism we so call "NEW WORLD".
		The "NEW WORLD" is a new world.
		Please enjoy this non stress and comfortable world.
	</p>

	<!-- Feature -->
	<section class="float left">
		<h3>Feature</h3>
		<ul>
			<li><a href="end-point/">End-Point</a></li>
			<li><a href="end-point/sub-directory/">Sub directory</a></li>
			<li><a href="html_pass_through.html">Html pass through</a></li>
			<li>Template files are located in asset/template.</li>
			<li>Layout files are located in asset/layout.</li>
		</ul>
	</section>
	<br class="float clear both"/>
</section>

<!-- Separator -->
<hr class="float clear both"/>

<!-- Developer -->
<section>
	<h2>Built-in Service</h2>
<?php if( file_exists( OP::ConvertPath('app:/_develop/', false) ) ): ?>
	<!-- Link is exists -->
	<section>
		<ul>
			<li><a href="./_develop/">develop</a></li>
		</ul>
	</section>
<?php else: ?>
	<!-- Link is not exists -->
	<section>
		<p>Please enter the next command.</p>
		<div class="code padding top left right bottom half">
			<div class="padding left half">
			<code>cd <?= $app_root ?></code><br/>
			<code>ln -s <?= $asset_path ?>develop _develop</code>
			</div>
		</div>
	</section>
<?php endif; ?>
</section>

<?php
/**
 * @deprecated 2022-10-08
 */
return;

/** use
 *
 * @created   2019-12-09
 */
use function OP\APP\FUNC\GetLinkList;

//	...
require_once( ConvertPath('asset:/function/welcome.php') );
$list = GetLinkList();

?>

<!-- Already linked -->
<section>
	<h2>Built-in Service</h2>
	<ul>
	<?php foreach( $list as $name => $path ): ?>
			<li class="<?= $path ? '':'gray' ?>">
				<?php if( $path ): ?>
					<a href="<?= $path ?>"><?= $name ?></a>
				<?php else: ?>
					<span class="gray"><?= $name ?></span>
				<?php endif; ?>
			</li>
	<?php endforeach; ?>
	</ul>
</section>

<!-- Not linked yet -->
<?php if( array_search(false, $list, true) ): ?>
<section>
<h2>Example</h2>
<pre><code><?php /* pre tag designe is feces */ ?>
cd <?= $app_root ?><br/>
<?php
foreach( $list as $name => $path ){
	//	...
	if( $path !== false ){
		continue;
	}

	//	...
	echo "ln -s {$asset_path}{$name} _{$name}<br/>";
}
?>
</code></pre>
</section>
<?php endif; ?>
