<?php
/**
 * app-skeleton-2019-nep:/asset/template/welcome.phtml
 *
 * @creation  2017-07-28
 * @version   1.0
 * @package   app-skeleton-2019-nep
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @creation  2019-02-22
 */
namespace OP;

/* @var $app UNIT\App */
$app->Title('Welcome');

?>
<style>
#welcome img {
	float: left;
	width: 10em;
	margin-right:  1em;
	margin-bottom: 1em;
}
</style>
<section id="welcome">
	<!-- Introduction -->
	<h2>Welcome to the onepiece-framework!!</h2>
	<img src="<?= ConvertURL('app:/img/icon.png') ?>" />
	<p>
		Congratulations! onepiece-framework would booted!!
		How was it? Have you boot easily? Yes, The onepiece-framework is insanely great!!
		Because, the onepiece-framework is everything is intuitive.
	</p>
	<p>
		For example, you can easily find the file of endpoint.
		Please refer to this page's URL, Directories are intact.
		We this mechanism so call "NEW WORLD".
		The "NEW WORLD" is a new world.
		Please enjoy this non stress and comfortable world.
	</p>

	<!-- Feature -->
	<section class="float left">
		<h3>Feature</h3>
		<ul>
			<li><a href="html_pass_through.html">Html pass through</a></li>
		</ul>
	</section>
</section>
<?php
if(!Env::isLocalhost() ){
	return;
};

//	...
$links = [];

//	...
$app_root = ConvertPath('app:/');

//	...
foreach( scandir($app_root) as $file ){
	//	...
	$path = $app_root . $file;

	//	...
	if( is_link($path) ){
		//	Get real directory name.
		$link = readlink($path);
		$link = rtrim($link, '/');
		$temp = explode('/', $link);
		$real = array_pop($temp);
		//	Get alias file name.
		$temp = explode('/', $path);
		$link = array_pop($temp);
		//	Joint.
		$links[$real] = $app->URL($path);
	};
};

//	...
echo '<hr style="clear:both;" />';

//	...
$asset_root = (ConvertPath('app:/asset/') === ConvertPath('asset:/')) ? './asset/': ConvertPath('asset:/');

//	...
$ok = $ng = [];
foreach( ['test','reference','develop'] as $key ){
	if( isset($links[$key]) ){
		$ok[] = $key;
	}else{
		$ng[] = $key;
	}
}

//	...
if( $ok ){
	echo '<ul>';
	foreach( $ok as $key ){
		$name = $key;
		$link = $links[$key];
		echo "<li><a href=\"$link\">$name</a></li>";
	};
	echo '</ul>';
};

//	...
if( $ng ){
	//	...
	echo '<section>';
	echo '<h2>Example</h2>';
	echo '<pre><code>';
	echo "cd $app_root<br/>\n";

	//	...
	foreach( $ng as $key ){
		if( empty($links[$key]) ){
			echo "ln -s {$asset_root}{$key} _{$key}<br/>";
		};
	}

	//	...
	echo '</code></pre>';
	echo '</section>';
}
