<?php
/**
 * app-skeleton-2020-nep:/asset/template/welcome.phtml
 *
 * @created   2017-07-28
 * @version   1.0
 * @package   app-skeleton-2019-nep
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @created   2019-02-22
 */
namespace OP;

/** use
 *
 * @created   2019-12-09
 */
use function OP\APP\FUNC\GetLinkList;

/* @var $app UNIT\App */
$app->Title('Welcome');

//	Get app root.
$app_root   = ConvertPath('app:/');
$asset_root = ConvertPath('asset:/');
$asset_path = null;

//	Calc asset path.
if( strpos($asset_root, $app_root) === 0 ){
	$asset_path = substr($asset_root, strlen($app_root) -1);
}else{
	$asset_path = $asset_root;
}

//	...
require_once( ConvertPath('asset:/function/welcome.php') );
$list = GetLinkList();

?>
<style>
#welcome img {
	float: left;
	width: 10em;
	margin-right:  1em;
	margin-bottom: 1em;
}
</style>
<section id="welcome">
	<!-- Introduction -->
	<h2>Welcome to the onepiece-framework!!</h2>
	<img src="<?= ConvertURL('app:/img/icon.png') ?>" />
	<p>
		Congratulations! onepiece-framework would booted!!
		How was it? Have you boot easily? Yes, The onepiece-framework is insanely great!!
		Because, the onepiece-framework is everything is intuitive.
	</p>
	<p>
		For example, you can easily find the file of endpoint.
		Please refer to this page's URL, Directories are intact.
		We this mechanism so call "NEW WORLD".
		The "NEW WORLD" is a new world.
		Please enjoy this non stress and comfortable world.
	</p>

	<!-- Feature -->
	<section class="float left">
		<h3>Feature</h3>
		<ul>
			<li><a href="html_pass_through.html">Html pass through</a></li>
		</ul>
	</section>
	<br class="float clear both"/>
</section>

<!-- Separator -->
<hr class="float clear both"/>

<!-- Already linked -->
<section>
	<h2>Built-in Service</h2>
	<ul>
	<?php foreach( $list as $name => $path ): ?>
		<?php if( $path !== false ): ?>
			<li><a href="<?= $path ?>"><?= $name ?></a></li>
		<?php endif; ?>
	<?php endforeach; ?>
	</ul>
</section>

<!-- Not linked yet -->
<?php if( array_search(false, $list, true) ): ?>
<section>
<h2>Example</h2>
<pre><code>
cd <?= $app_root ?><br/>
<?php
foreach( $list as $name => $path ){
	//	...
	if( $path !== false ){
		continue;
	}

	//	...
	echo "ln -s {$asset_path}{$name} _{$name}<br/>";
}
?>
</code></pre>
</section>
<?php endif; ?>
