<?php
/**
 * app-skeleton-2020-nep:/asset/template/layout/footer.phtml
 *
 * @creation  2018-04-12
 * @version   1.0
 * @package   app-skeleton-2020-nep
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @creation  2019-04-03
 */
namespace OP;

/* @var $app UNIT\App */
Template('google/analytics.phtml');

?>
<footer>
	<?= Env::Get('app')['copyright'] ?? null ?>
</footer>
