<?php
/** op-skeleton-2020:/asset/template/head.php
 *
 * @creation  2018-04-12
 * @version   1.0
 * @package   op-skeleton-2020
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 */
namespace OP;

//	...
$app_root= ConvertURL('app:/');
$charset = Config::Get('html')  ['charset'] ?? 'utf-8';
$layout  = Config::Get('layout')['name']    ??  null;

//	...
$hash_js  = Unit('WebPack')->FileContentHash('js');
$hash_css = Unit('WebPack')->FileContentHash('css');
?>
	<!-- Charset -->
	<meta charset="<?= $charset ?>" />
	<meta http-equiv="Content-Type"  content="text/html; charset=<?= $charset ?>" />

	<!-- For SmartPhone -->
	<!-- Disable auto scaling -->
	<meta name="viewport"            content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
	<!-- Disable phone number highlight -->
	<meta name="format-detection"    content="telephone=no" />

	<!-- Canonical -->
	<link rel="canonical" href="" />

	<!-- Icon -->
	<link type="image/x-icon" href="<?= "{$app_root}img/favicon.ico" ?>" rel="icon" />
	<link type="image/png"    href="<?= "{$app_root}img/icon.png" ?>"    rel="apple-touch-icon" />
	<link type="image/png"    href="<?= "{$app_root}img/icon.png" ?>"    rel="apple-touch-icon-precomposed" />

	<!-- Stylesheet -->
	<link type="text/css" href="<?= "{$app_root}css/index.css?layout={$layout}&hash={$hash_css}" ?>" rel="stylesheet">

	<!-- JavaScript -->
	<script type="text/javascript" src="<?= "{$app_root}js/index.js?layout={$layout}&hash={$hash_js}" ?>" defer></script>

	<!-- title -->
	<title><?= OP()->App()->Title() ?></title>
