<?php
/**
 * app-skeleton-2020-nep:/asset/template/head.php
 *
 * @creation  2018-04-12
 * @version   1.0
 * @package   app-skeleton-2020-nep
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 */
namespace OP;

/** use
 *
 */
use OP\UNIT\App;

/* @var $app UNIT\App */

//	...
$app_root= ConvertURL('app:/');
$charset = Env::Get('app')   ['charset'] ?? 'utf-8';
$layout  = Env::Get('layout')['name']    ??  null;

//	...
$hash_js  = Unit('WebPack')->FileContentHash('js');
$hash_css = Unit('WebPack')->FileContentHash('css');

?>
	<!-- Charset -->
	<meta charset="<?= $charset ?>" />
	<meta http-equiv="Content-Type"  content="text/html; charset=<?= $charset ?>" />

	<!-- For SmartPhone -->
	<!-- Disable auto scaling -->
	<meta name="viewport"            content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
	<!-- Disable phone number highlight -->
	<meta name="format-detection"    content="telephone=no" />

	<!-- Canonical -->
	<link rel="canonical" href="<?= App::Canonical() ?>" />

	<!-- Icon -->
	<link type="image/x-icon" href="<?= "{$app_root}img/favicon.ico" ?>" rel="icon" />
	<link type="image/png"    href="<?= "{$app_root}img/icon.png" ?>"    rel="apple-touch-icon" />
	<link type="image/png"    href="<?= "{$app_root}img/icon.png" ?>"    rel="apple-touch-icon-precomposed" />

	<!-- Stylesheet -->
	<link type="text/css" href="<?= "{$app_root}webpack/css/?layout={$layout}&hash={$hash_css}" ?>" rel="stylesheet">

	<!-- JavaScript -->
	<script type="text/javascript" src="<?= "{$app_root}webpack/js/?layout={$layout}&hash={$hash_js}" ?>" defer></script>
	<?php Template('i18n_load_script.phtml'); ?>

	<!-- title -->
	<title><?= App::Title() ?></title>
