<?php
/** op-skeleton-2020:/asset/template/layout/header.phtml
 *
 * @creation  2018-04-12
 * @version   1.0
 * @package   op-skeleton-2020
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @creation  2019-03-01
 */
namespace OP;

//	...
if( Env::isAdmin() ){
	echo '<!-- '.ConvertURL(__FILE__).' -->';
}

?>
<header>
	<a href="<?= ConvertURL('app:/') ?>"><?= Config::Get('app')['title'] ?? 'TOP' ?></a>
</header>
