<?php
/**
 * app-skeleton-2020-nep:/asset/template/layout/header.phtml
 *
 * @creation  2018-04-12
 * @version   1.0
 * @package   app-skeleton-2020-nep
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @creation  2019-03-01
 */
namespace OP;

/* @var $app UNIT\App */
?>
<header>
	<a href="<?= ConvertURL('app:/') ?>"><?= Env::Get('app')['title'] ?? 'TOP' ?></a>
</header>
