<?php
/**
 * app-skeleton-2020-nep:/asset/template/layout/footer.phtml
 *
 * @created   2020-01-20
 * @version   1.0
 * @package   app-skeleton-2020-nep
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @created   2020-01-20
 */
namespace OP;

//	Load i18n URL
if(!Config::Get('i18n')['url'] ?? null ){
	return;
}

?>
<section>
	<nav>
		<div id="unit-i18n-language">
			<div class="language-outline">
				<div class="language-message" data-i18n="true" data-i18n-locale="en:us">
					You can select the translation destination language.
				</div>
				<div class="language-area"></div>
				<div class="language-toggle clickable" data-i18n-language-icon-show='▼' data-i18n-language-icon-hide='▲'>●</div><br style="clear:both;"/>
			</div>
		</div>
	</nav>
</section>
<style>
#unit-i18n-language .language-outline {
	margin:  1px;
	padding: 1px;
	border:  1px solid black;
}

#unit-i18n-language .language-message {
	font-weight: bold;
	float: left;
}

#unit-i18n-language .language-area {
	padding-top:  0.5em;
	padding-left: 1.0em;
	float: left;
}

#unit-i18n-language .language-area span {
	margin-right: 1em;
	border: transparent 1px solid;
	display: inline-block;
}

#unit-i18n-language .language-area span.language.current {
	background-color: yellow;
}

#unit-i18n-language .language-area span:hover {
	border: 1px solid #333;
	background-color: yellow;
}

#unit-i18n-language .language-toggle {
	margin: 0.5em;
	float: right;
}
</style>
