<?php
/**
 * app-skeleton-2020-nep:/asset/template/layout/footer.phtml
 *
 * @created   2020-01-20
 * @version   1.0
 * @package   app-skeleton-2020-nep
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @created   2020-01-20
 */
namespace OP;

?>
<section>
	<nav>
		<div id="unit-i18n-language">
			<div class="language-outline">
				<div class="language-area"></div>
				<div class="language-toggle" data-i18n-language-icon-show='▼' data-i18n-language-icon-hide='▲'>●</div><br style="clear:both;"/>
			</div>
		</div>
	</nav>
</section>
<script>
window.addEventListener('DOMContentLoaded', function(event){

});
</script>
<style>
#unit-i18n-language .language-outline {
	margin:  1px;
	padding: 1px;
	border:  1px solid black;
}

#unit-i18n-language .language-area {
	padding-top:  0.5em;
	padding-left: 1.0em;
}

#unit-i18n-language .language-area span {
	margin-right: 1em;
	border: 1px solid white;
	display: inline-block;
}

#unit-i18n-language .language-area span.language.current {
	background-color: yellow;
}

#unit-i18n-language .language-area span:hover {
	border: 1px solid #333;
	background-color: yellow;
}

#unit-i18n-language .language-toggle {
	margin: 0.5em;
	float: right;
}
</style>
