<?php
/**
 * app-skeleton-2020-nep:/i18n.phtml
 *
 * @created   2020-01-21
 * @version   1.0
 * @package   app-skeleton-2020-nep
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @created   2020-01-21
 */
namespace OP;

//	Get config.
$config = OP::Config('translate');

//	Execute?
if(!$config['execute'] ?? false ){
	return;
}
